# This file provides explicit instructions for Netlify

[build]
  # This tells Netlify where your website files are. 
  # "." means the current directory.
  publish = "."
  
  # This tells Netlify where your serverless functions are located.
  functions = "netlify/functions"

[dev]
  # This mirrors the build settings for the local 'netlify dev' command
  publish = "."
  functions = "netlify/functions"

# This rule ensures that POST requests to your function's endpoint
# are correctly routed to the function itself.
[[redirects]]
  from = "/.netlify/functions/subscribe"
  to = "/.netlify/functions/subscribe"
  status = 200